# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    commands:
      - curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      - sudo source ~/.bashrc
      - sudo nvm install 18.19.0
      - sudo nvm use 18.19.0

  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run compile
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  baseDirectory: build
  files:
    - build/**/*
    - appspec.yml
    - scripts/**/*
