export enum responseName {
  ok = 'OK',
  created = 'Created',
  failure = 'Failure',
}

export enum paymentPlatform {
  easypay = 'Easypay direct',
  seamlesschex = 'Seamlesschex',
}

export enum permissions {
  createNewCase = 'createNewCase',
  importBulkCases = 'importBulkCases',
  viewUserListing = 'viewUserListing',
  addNewUser = 'addNewUser',
  deleteUser = 'deleteUser',
  createAdminUser = 'createAdminUser',
  viewHomeScreen = 'viewHomeScreen',
  viewPaymentsAndAuthorizations = 'viewPaymentsAndAuthorizations',
  retryPayment = 'retryPayment',
  retryCapture = 'retryCapture',
  viewCaseDetails = 'viewCaseDetails',
  viewClientsForSelf = 'viewClientsForSelf',
  viewClientsForAllUsers = 'viewClientsForAllUsers',
  viewCreditorsForSelf = 'viewCreditorsForSelf',
  viewCreditorsForAllUsers = 'viewCreditorsForAllUsers',
  editPaymentsNotificationSettings = 'editPaymentsNotificationSettings',
  editAuthorizationInterval = 'editAuthorizationInterval',
  editRetryInterval = 'editRetryInterval',
  viewNotificationTemplates = 'viewNotificationTemplates',
  viewCustomFields = 'viewCustomFields',
  addNotificationTemplate = 'addNotificationTemplate',
  editNotificationTemplate = 'editNotificationTemplate',
  addCustomFields = 'addCustomFields',
  deleteNotificationTemplate = 'deleteNotificationTemplate',
  editCustomFields = 'editCustomFields',
  deleteCustomFields = 'deleteCustomFields',
  viewCaseStatuses = 'viewCaseStatuses',
  addCaseStatus = 'addCaseStatus',
  editCaseStatus = 'editCaseStatus',
  deleteCaseStatus = 'deleteCaseStatus',
  viewPipeline = 'viewPipeline',
  createPipeline = 'createPipeline',
  editPipeline = 'editPipeline',
  deletePipeline = 'deletePipeline',
  addRole = 'addRole',
  updateRole = 'updateRole',
  deleteRole = 'deleteRole',
  viewAnalyticsForSelf = 'viewAnalyticsForSelf',
  viewAnalyticsForAllusers = 'viewAnalyticsForAllusers',
}

export enum Events {
  failed_authorization = 'failed_authorization',
  successful_authorization = 'successful_authorization',
  failed_payment = 'failed_payment',
  successful_payment = 'successful_payment',
  upcoming_payment = 'upcoming_payment',
  case_task_added = 'case_task_added',
  case_task_due_data_near = 'case_task_due_data_near',
  case_task_assigned = 'case_task_assigned',
  case_task_unassigned = 'case_task_unassigned',
  case_note_added = 'case_note_added',
  case_owner_changed = 'case_owner_changed',
  case_negotiator_changed = 'case_negotiator_changed',
  case_manager_changed = 'case_manager_changed',
  case_details_update = 'case_details_update',
}

export enum User {
  admin = 'Admin',
  negotiator = 'Negotiator',
  case_Manager = 'Case Manager',
  debtor = 'Debtor',
  creditor = 'Creditor',
}
