import mongoose, {Document} from 'mongoose';

export interface IPayment extends Document {
  caseId: mongoose.Schema.Types.ObjectId;
  attorneyId: mongoose.Schema.Types.ObjectId;
  lawsuitId: mongoose.Schema.Types.ObjectId;
  debtorId: string;
  authorized: string;
  captured: string;
  status: string;
  sendViaPaynote: string;
  paynoteCheckId: string;
  amount: number;
  previousAmount: number;
  dueDate: string;
  frequency: number;
  intervalId: string;
  failedReasonAuthorization: string;
  failedReasonCaptured: string;
  failedReasonPaynote: string;
  rescheduled: string;
  debtorTransId: string;
  retriesAuth: number;
  retriesCapture: number;
  retriesPaynote: number;
  timePeriod: string;
  paymentReference: string;
  isDeleted: boolean;
  paymentReferenceBool: boolean;
  commission: number;
  createdAt: string;
  updatedAt: string;
  transactionType: string;
  paymentGateway: string;
  manualCommission: number;
  paymentLink: string;
  debtorName: string;
  authorizedDate: string;
  serviceFee: number;
  legalFee: number;
  paymentMode: string;
  calculateComission: boolean;
}
