import commonUtil from '../../utils/common.util';

export class Payment {
  caseId = null;
  attorneyId = null;
  debtorId = '';
  authorized = 'Pending';
  captured = 'Pending';
  status = 'Upcoming';
  sendViaPaynote = 'Pending';
  paynoteCheckId = '';
  amount = 0;
  dueDate = '';
  frequency = 0;
  intervalId = '';
  failedReasonAuthorization = '';
  failedReasonCaptured = '';
  failedReasonPaynote = '';
  rescheduled = '';
  debtorTransId = '';
  retriesAuth = 0;
  retriesCapture = 0;
  retriesPaynote = 0;
  timePeriod = '';
  paymentReference = '';
  isDeleted = false;
  paymentReferenceBool = false;
  commission = 0;
  createdAt = commonUtil.getCurrentDate();
  updatedAt = commonUtil.getCurrentDate();
  transactionType = '';
  paymentGateway = '';
  manualCommission = 0;
  paymentLink = '';
  debtorName = '';
  authorizedDate = '';
  serviceFee = 0;
  legalFee = 0;
  creditorName = '';
}
